In [11]:
%load_ext autoreload
%autoreload 2
import pandas as pd

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Save only 2021 accident dataset

In [29]:
#csv_path = '/home/linnanchen/code/MagicaBleps/UK-road-safety/raw_data'
#df_accident = pd.read_csv(os.path.join(csv_path, 'dft-road-casualty-statistics-accident-1979-2021.csv'))
#df_accident = df_accident[df_accident['accident_year'] >= 2021]
#df_accident.head()
#df_accident.to_csv('df_accident_2021.csv')

/tmp/ipykernel_9652/341685357.py:2: DtypeWarning: Columns (0,2,15,16,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df_accident = pd.read_csv(os.path.join(csv_path, 'dft-road-casualty-statistics-accident-1979-2021.csv'))

,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,...,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
8602824,2021010287148,2021,10287148,521508.0,193079.0,-0.246102,51.623425,1,3,3,...,0,4,7,4,1,0,1,1,2,E01000263
8602825,2021010287149,2021,10287149,535379.0,180783.0,-0.050574,51.509767,1,2,2,...,5,4,1,1,0,0,1,1,2,E01004303
8602826,2021010287151,2021,10287151,529701.0,170398.0,-0.136152,51.417769,1,2,2,...,5,4,1,1,0,0,1,1,2,E01003146
8602827,2021010287155,2021,10287155,525312.0,178385.0,-0.196411,51.490536,1,1,1,...,4,4,1,1,0,0,1,1,2,E01002847
8602828,2021010287157,2021,10287157,512144.0,171526.0,-0.388169,51.431649,1,3,4,...,0,4,1,1,0,0,1,1,2,E01002608

## Add columns function:
 'date','weekday',"IsWeekend",'month','Daytime'

In [30]:
csv_path = '/home/linnanchen/code/MagicaBleps/UK-road-safety/notebooks'

In [31]:
df = pd.read_csv('df_accident_2021.csv')
df.head()

/tmp/ipykernel_9652/3478360571.py:1: DtypeWarning: Columns (1,3,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('df_accident_2021.csv')

,Unnamed: 0,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,...,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
0,8602824,2021010287148,2021,10287148,521508.0,193079.0,-0.246102,51.623425,1,3,...,0,4,7,4,1,0,1,1,2,E01000263
1,8602825,2021010287149,2021,10287149,535379.0,180783.0,-0.050574,51.509767,1,2,...,5,4,1,1,0,0,1,1,2,E01004303
2,8602826,2021010287151,2021,10287151,529701.0,170398.0,-0.136152,51.417769,1,2,...,5,4,1,1,0,0,1,1,2,E01003146
3,8602827,2021010287155,2021,10287155,525312.0,178385.0,-0.196411,51.490536,1,1,...,4,4,1,1,0,0,1,1,2,E01002847
4,8602828,2021010287157,2021,10287157,512144.0,171526.0,-0.388169,51.431649,1,3,...,0,4,1,1,0,0,1,1,2,E01002608

In [32]:
df.columns

Index(['Unnamed: 0', 'accident_index', 'accident_year', 'accident_reference',
       'location_easting_osgr', 'location_northing_osgr', 'longitude',
       'latitude', 'police_force', 'accident_severity', 'number_of_vehicles',
       'number_of_casualties', 'date', 'day_of_week', 'time',
       'local_authority_district', 'local_authority_ons_district',
       'local_authority_highway', 'first_road_class', 'first_road_number',
       'road_type', 'speed_limit', 'junction_detail', 'junction_control',
       'second_road_class', 'second_road_number',
       'pedestrian_crossing_human_control',
       'pedestrian_crossing_physical_facilities', 'light_conditions',
       'weather_conditions', 'road_surface_conditions',
       'special_conditions_at_site', 'carriageway_hazards',
       'urban_or_rural_area', 'did_police_officer_attend_scene_of_accident',
       'trunk_road_flag', 'lsoa_of_accident_location'],
      dtype='object')

In [33]:
df['day_of_week']

0         6
1         6
2         6
3         6
4         6
         ..
101082    4
101083    7
101084    7
101085    6
101086    6
Name: day_of_week, Length: 101087, dtype: int64

In [34]:
# add column "day_night"
df['Daytime'] = df['time'].apply(lambda x: "morning rush (5-10)" if '05:00' < x <= '10:00' 
                                   else ("office hours (10-15)" if '10:00' < x <= '15:00' 
                                         else( "afternoon rush (15-19)" if '15:00' < x <= '19:00'
                                              else ("evening (19-23)" if '19:00' < x <= '23:00'
                                                    else("night (23-5")))))
df.head()

,Unnamed: 0,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,...,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,Daytime
0,8602824,2021010287148,2021,10287148,521508.0,193079.0,-0.246102,51.623425,1,3,...,4,7,4,1,0,1,1,2,E01000263,night (23-5
1,8602825,2021010287149,2021,10287149,535379.0,180783.0,-0.050574,51.509767,1,2,...,4,1,1,0,0,1,1,2,E01004303,night (23-5
2,8602826,2021010287151,2021,10287151,529701.0,170398.0,-0.136152,51.417769,1,2,...,4,1,1,0,0,1,1,2,E01003146,night (23-5
3,8602827,2021010287155,2021,10287155,525312.0,178385.0,-0.196411,51.490536,1,1,...,4,1,1,0,0,1,1,2,E01002847,night (23-5
4,8602828,2021010287157,2021,10287157,512144.0,171526.0,-0.388169,51.431649,1,3,...,4,1,1,0,0,1,1,2,E01002608,night (23-5

In [35]:
df['Daytime'].values

array(['night (23-5', 'night (23-5', 'night (23-5', ...,
       'office hours (10-15)', 'afternoon rush (15-19)',
       'afternoon rush (15-19)'], dtype=object)

In [39]:
# add column "weekday_weekend"
df["date"] = pd.to_datetime(df["date"])
df['weekday'] =  df['date'].dt.weekday
df["IsWeekend"] = df['date'].dt.weekday > 5

In [37]:
# add column "month"
df['month'] = df['date'].dt.month

In [38]:
df[['date','weekday',"IsWeekend",'month','Daytime']]

             date  weekday  IsWeekend  month                 Daytime
0      2021-01-01        4      False      1             night (23-5
1      2021-01-01        4      False      1             night (23-5
2      2021-01-01        4      False      1             night (23-5
3      2021-01-01        4      False      1             night (23-5
4      2021-01-01        4      False      1             night (23-5
...           ...      ...        ...    ...                     ...
101082 2021-09-22        2      False      9     morning rush (5-10)
101083 2021-11-09        1      False     11         evening (19-23)
101084 2021-04-17        5      False      4    office hours (10-15)
101085 2021-09-17        4      False      9  afternoon rush (15-19)
101086 2021-10-15        4      False     10  afternoon rush (15-19)

[101087 rows x 5 columns]