In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd

## create dataset from 1999 - 2019

In [2]:
csv_path = '/home/linnanchen/code/MagicaBleps/UK-road-safety/raw_data'
df_accident = pd.read_csv(os.path.join(csv_path, 'dft-road-casualty-statistics-accident-1979-2021.csv'))
#df_accident = df_accident[(df_accident['accident_year'] >= 1999) & (df_accident['accident_year'] <= 2019)]
df_accident.head()
#df_accident.to_csv('df_accident_19b99_2019.csv')

/tmp/ipykernel_11216/2636704368.py:2: DtypeWarning: Columns (0,2,15,16,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df_accident = pd.read_csv(os.path.join(csv_path, 'dft-road-casualty-statistics-accident-1979-2021.csv'))

,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,...,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
0,197901A11AD14,1979,01A11AD14,NaN,NaN,NaN,NaN,1,3,2,...,-1,1,8,1,-1,0,-1,-1,-1,-1
1,197901A1BAW34,1979,01A1BAW34,198460.0,894000.0,NaN,NaN,1,3,1,...,-1,4,8,3,-1,0,-1,-1,-1,-1
2,197901A1BFD77,1979,01A1BFD77,406380.0,307000.0,NaN,NaN,1,3,2,...,-1,4,8,3,-1,0,-1,-1,-1,-1
3,197901A1BGC20,1979,01A1BGC20,281680.0,440000.0,NaN,NaN,1,3,2,...,-1,4,8,3,-1,0,-1,-1,-1,-1
4,197901A1BGF95,1979,01A1BGF95,153960.0,795000.0,NaN,NaN,1,2,2,...,-1,4,3,3,-1,0,-1,-1,-1,-1

In [3]:
df_1999_2019 = df_accident[(df_accident['accident_year'] >= 1999) & (df_accident['accident_year'] <= 2019)]
df_1999_2019.to_csv(os.path.join(csv_path,'df_accident_1999_2019.csv'))

## Add columns function:
 'date','weekday',"IsWeekend",'month','Daytime'

In [5]:
csv_path = '/home/linnanchen/code/MagicaBleps/UK-road-safety/raw_data'
df = pd.read_csv(os.path.join(csv_path,'df_accident_1999_2019.csv'))
df.head()

/tmp/ipykernel_11216/116672672.py:2: DtypeWarning: Columns (1,3,36) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(csv_path,'df_accident_1999_2019.csv'))

,Unnamed: 0,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,...,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
0,4883216,1999010SU0945,1999,010SU0945,519490.0,203300.0,-0.271752,51.715661,1,3,...,0,1,4,1,0,0,2,1,1,E01023583
1,4883217,1999010SU0946,1999,010SU0946,521740.0,201070.0,-0.239977,51.695136,1,3,...,0,6,4,1,0,0,2,1,1,E01023584
2,4883218,1999010SU0947,1999,010SU0947,519610.0,203240.0,-0.270037,51.715096,1,3,...,0,4,1,2,0,0,2,1,1,E01023583
3,4883219,1999010SU0948,1999,010SU0948,520090.0,202830.0,-0.263233,51.711309,1,2,...,0,6,1,1,0,0,2,1,1,E01023583
4,4883220,1999010SU0949,1999,010SU0949,522640.0,200320.0,-0.227225,51.688200,1,3,...,0,1,1,2,0,0,2,1,1,E01023584

In [6]:
df.columns

Index(['Unnamed: 0', 'accident_index', 'accident_year', 'accident_reference',
       'location_easting_osgr', 'location_northing_osgr', 'longitude',
       'latitude', 'police_force', 'accident_severity', 'number_of_vehicles',
       'number_of_casualties', 'date', 'day_of_week', 'time',
       'local_authority_district', 'local_authority_ons_district',
       'local_authority_highway', 'first_road_class', 'first_road_number',
       'road_type', 'speed_limit', 'junction_detail', 'junction_control',
       'second_road_class', 'second_road_number',
       'pedestrian_crossing_human_control',
       'pedestrian_crossing_physical_facilities', 'light_conditions',
       'weather_conditions', 'road_surface_conditions',
       'special_conditions_at_site', 'carriageway_hazards',
       'urban_or_rural_area', 'did_police_officer_attend_scene_of_accident',
       'trunk_road_flag', 'lsoa_of_accident_location'],
      dtype='object')

In [7]:
df['day_of_week']

0          7
1          6
2          4
3          5
4          7
          ..
3628404    7
3628405    5
3628406    6
3628407    7
3628408    1
Name: day_of_week, Length: 3628409, dtype: int64

In [ ]:
# add column "day_night"
df['Daytime'] = df['time'].apply(lambda x: "morning rush (5-10)" if '05:00' < x <= '10:00' 
                                   else ("office hours (10-15)" if '10:00' < x <= '15:00' 
                                         else( "afternoon rush (15-19)" if '15:00' < x <= '19:00'
                                              else ("evening (19-23)" if '19:00' < x <= '23:00'
                                                    else("night (23-5")))))
df.head()

In [ ]:
df['Daytime'].values

In [ ]:
# add column "weekday_weekend"
df["date"] = pd.to_datetime(df["date"])
df['weekday'] =  df['date'].dt.weekday
df["IsWeekend"] = df['date'].dt.weekday > 5

In [ ]:
# add column "month"
df['month'] = df['date'].dt.month

In [ ]:
df[['date','weekday',"IsWeekend",'month','Daytime']]

## Prediction baseline model

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from tensorflow.keras.layers import Normalization
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Flatten
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
norm = Normalization()
norm.adapt(X_train)

In [ ]:
model = Sequential()

model.add(norm)
model.add(SimpleRNN(20, activation='tanh'))
model.add(Dense(10, activation="relu"))
model.add(Dense(1, activation="linear"))


model.compile(loss='mse', optimizer='rmsprop', metrics=['mae'])

es = EarlyStopping(patience=5)

history = model.fit(X_train, y_train,
                    validation_split = 0.2,
                    batch_size=16, 
                    epochs=10,
                    callbacks=[es],
                    verbose=1,
                    )

In [ ]:
res = model.evaluate(X_test, y_test)
res