In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd

In [4]:
csv_path = '/home/linnanchen/code/MagicaBleps/UK-road-safety/raw_data'

In [5]:
df_accident = pd.read_csv(os.path.join(csv_path, 'dft-road-casualty-statistics-accident-1979-2021.csv'))
df_accident.head()

/tmp/ipykernel_25868/209948914.py:1: DtypeWarning: Columns (0,2,15,16,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df_accident = pd.read_csv(os.path.join(csv_path, 'dft-road-casualty-statistics-accident-1979-2021.csv'))

,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,...,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
0,197901A11AD14,1979,01A11AD14,NaN,NaN,NaN,NaN,1,3,2,...,-1,1,8,1,-1,0,-1,-1,-1,-1
1,197901A1BAW34,1979,01A1BAW34,198460.0,894000.0,NaN,NaN,1,3,1,...,-1,4,8,3,-1,0,-1,-1,-1,-1
2,197901A1BFD77,1979,01A1BFD77,406380.0,307000.0,NaN,NaN,1,3,2,...,-1,4,8,3,-1,0,-1,-1,-1,-1
3,197901A1BGC20,1979,01A1BGC20,281680.0,440000.0,NaN,NaN,1,3,2,...,-1,4,8,3,-1,0,-1,-1,-1,-1
4,197901A1BGF95,1979,01A1BGF95,153960.0,795000.0,NaN,NaN,1,2,2,...,-1,4,3,3,-1,0,-1,-1,-1,-1

In [6]:
df_casualty = pd.read_csv(os.path.join(csv_path, 'dft-road-casualty-statistics-casualty-1979-2021.csv'))
df_casualty.head()

/tmp/ipykernel_25868/911384059.py:1: DtypeWarning: Columns (0,2,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_casualty = pd.read_csv(os.path.join(csv_path, 'dft-road-casualty-statistics-casualty-1979-2021.csv'))

,accident_index,accident_year,accident_reference,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_home_area_type,casualty_imd_decile,lsoa_of_casualty
0,197901A11AD14,1979,01A11AD14,2,1,1,1,-1,-1,3,0,0,0,0,-1,104,-1,-1,-1
1,197901A1BAW34,1979,01A1BAW34,1,1,3,2,27,6,3,10,5,0,0,-1,0,-1,-1,-1
2,197901A1BFD77,1979,01A1BFD77,1,1,1,1,21,5,3,0,0,0,0,-1,109,-1,-1,-1
3,197901A1BFD77,1979,01A1BFD77,1,2,2,1,20,4,3,0,0,1,0,-1,109,-1,-1,-1
4,197901A1BFD77,1979,01A1BFD77,2,3,1,1,35,6,3,0,0,0,0,-1,109,-1,-1,-1

In [7]:
#df_vehicle = pd.read_csv(os.path.join(csv_path, 'dft-road-casualty-statistics-vehicle-1979-2021.csv'))

In [17]:
df_accident = df_accident[df_accident['accident_year'] >= 2018]
df_accident.head()

,accident_index,accident_year,accident_reference,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,...,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
8271454,2018010080971,2018,010080971,529150.0,182270.0,-0.139737,51.524587,1,3,2,...,0,4,1,1,0,0,1,1,2,E01000854
8271455,2018010080973,2018,010080973,542020.0,184290.0,0.046471,51.539651,1,3,1,...,0,4,1,1,0,0,1,1,2,E01003531
8271456,2018010080974,2018,010080974,531720.0,182910.0,-0.102474,51.529746,1,3,2,...,5,4,1,1,0,0,1,1,2,E01002723
8271457,2018010080981,2018,010080981,541450.0,183220.0,0.037828,51.530179,1,2,2,...,5,4,2,2,0,0,1,1,2,E01003492
8271458,2018010080982,2018,010080982,543580.0,176500.0,0.065781,51.469258,1,2,2,...,0,4,1,2,0,0,1,1,2,E01001682

In [16]:
df_accident.shape

(839116, 36)

In [19]:
df_accident.isnull().sum()

accident_index                                   0
accident_year                                    0
accident_reference                               0
location_easting_osgr                          114
location_northing_osgr                         114
longitude                                      114
latitude                                       114
police_force                                     0
accident_severity                                0
number_of_vehicles                               0
number_of_casualties                             0
date                                             0
day_of_week                                      0
time                                             0
local_authority_district                         0
local_authority_ons_district                     0
local_authority_highway                          0
first_road_class                                 0
first_road_number                                0
road_type                                        0
speed_limit                                      0
junction_detail                                  0
junction_control                                 0
second_road_class                                0
second_road_number                               0
pedestrian_crossing_human_control                0
pedestrian_crossing_physical_facilities          0
light_conditions                                 0
weather_conditions                               0
road_surface_conditions                          0
special_conditions_at_site                       0
carriageway_hazards                              0
urban_or_rural_area                              0
did_police_officer_attend_scene_of_accident      0
trunk_road_flag                                  0
lsoa_of_accident_location                        0
dtype: int64